package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/obertcoy/tpa-web/graph"
	"github.com/obertcoy/tpa-web/graph/model"
	"github.com/obertcoy/tpa-web/graph/service"
	"github.com/obertcoy/tpa-web/helper"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, inputUser model.NewUser) (*model.User, error) {
	activateToken := uuid.NewString()

	user := &model.User{
		ID:            uuid.NewString(),
		FirstName:     inputUser.FirstName,
		LastName:      inputUser.LastName,
		Email:         inputUser.Email,
		Gender:        inputUser.Gender,
		Dob:           inputUser.Dob,
		Password:      helper.EncryptPassword(inputUser.Password),
		Activated:     false,
		ActivateToken: activateToken,
		ForgotToken:   uuid.NewString(),
	}

	helper.SendMail("Activate Account", activateToken)

	return user, r.Database.Save(&user).Error
}

// ActivateUser is the resolver for the activateUser field.
func (r *mutationResolver) ActivateUser(ctx context.Context, token string) (bool, error) {
	user, err := service.GetUserByActivateToken(ctx, token)

	if err != nil {
		return false, err
	}

	if token != user.ActivateToken {
		return false, err
	}

	user.Activated = true
	return true, r.Database.Save(&user).Error
}

// SendChangePassword is the resolver for the sendChangePassword field.
func (r *mutationResolver) SendChangePassword(ctx context.Context, email string) (bool, error) {
	user, err := service.GetUserByEmail(ctx, email)

	if err != nil {
		return false, err
	}

	helper.SendMail("Forgot Password", user.ForgotToken)

	return true, nil
}

// VerifyChangePasswordToken is the resolver for the verifyChangePasswordToken field.
func (r *mutationResolver) VerifyChangePasswordToken(ctx context.Context, email string, token string) (bool, error) {
	user, err := service.GetUserByEmail(ctx, email)

	if err != nil {
		return false, err
	}

	if token != user.ForgotToken {
		return false, err
	}

	return true, err
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, email string, newPassword string) (bool, error) {
	user, err := service.GetUserByEmail(ctx, email)

	if err != nil {
		return false, err
	}

	user.Password = helper.EncryptPassword(newPassword)
	return true, r.Database.Save(&user).Error
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, inputUser model.NewUser) (*model.User, error) {
	var user *model.User
	if err := r.Database.First(&user, "id = ?", id).Error; err != nil {
		return nil, err
	}
	user.FirstName = inputUser.FirstName
	user.LastName = inputUser.LastName
	user.Email = inputUser.Email
	user.Dob = inputUser.Dob
	user.Password = helper.EncryptPassword(inputUser.Password)

	return user, r.Database.Save(&user).Error
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.User, error) {
	var user *model.User
	if err := r.Database.First(&user, "id = ?", id).Error; err != nil {
		return nil, err
	}

	return user, r.Database.Delete(&user).Error
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, inputCredential model.LoginCredential) (*model.UserAuthorization, error) {
	user, err := service.GetActiveUserByEmail(ctx, inputCredential.Email)

	if err != nil {
		return nil, err
	}

	if helper.CheckPassword(user.Password, inputCredential.Password) {

		token, tokenErr := helper.GenerateJWTToken(user.ID)

		if tokenErr != nil {
			return nil, err
		}

		userAuthorization := &model.UserAuthorization{
			User:  user,
			Token: token,
		}

		fmt.Println(user, token)

		return userAuthorization, err
	}

	return nil, err
}

// UpdateProfileImage is the resolver for the updateProfileImage field.
func (r *mutationResolver) UpdateProfileImage(ctx context.Context, fileURL string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, err := service.GetUser(ctx, userID)

	if err != nil {
		return false, err
	}

	user.ProfileImageURL = &fileURL
	return true, r.Database.Save(&user).Error
}

// UpdateBannerImage is the resolver for the updateBannerImage field.
func (r *mutationResolver) UpdateBannerImage(ctx context.Context, fileURL string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, err := service.GetUser(ctx, userID)

	if err != nil {
		return false, err
	}

	user.BannerImageURL = &fileURL
	return true, r.Database.Save(&user).Error
}

// SendFriendRequest is the resolver for the sendFriendRequest field.
func (r *mutationResolver) SendFriendRequest(ctx context.Context, friendID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, userErr := service.GetUser(ctx, userID)
	friend, friendErr := service.GetUser(ctx, friendID)

	if userErr != nil || friendErr != nil {
		return false, userErr
	}

	friend.PendingFriend = append(friend.PendingFriend, user)
	return true, r.Database.Save(&friend).Error
}

// AcceptFriendRequest is the resolver for the AcceptFriendRequest field.
func (r *mutationResolver) AcceptFriendRequest(ctx context.Context, friendID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, userErr := service.GetUser(ctx, userID)
	friend, friendErr := service.GetUser(ctx, friendID)

	if userErr != nil || friendErr != nil {
		return false, userErr
	}

	err := r.Database.Model(&user).Association("PendingFriend").Delete(friend)
	if err != nil {
		return false, fmt.Errorf("Error accepting friend: %v", err)
	}
	user.Friend = append(user.Friend, friend)
	friend.Friend = append(friend.Friend, user)

	err = r.Database.Save(&friend).Error

	if err != nil {
		return false, err
	}

	return true, r.Database.Save(&user).Error
}

// RejectFriendRequest is the resolver for the RejectFriendRequest field.
func (r *mutationResolver) RejectFriendRequest(ctx context.Context, friendID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, userErr := service.GetUser(ctx, userID)
	friend, friendErr := service.GetUser(ctx, friendID)

	if userErr != nil || friendErr != nil {
		return false, userErr
	}

	err := r.Database.Model(&user).Association("PendingFriend").Delete(friend)
	if err != nil {
		return false, fmt.Errorf("Error reject friend: %v", err)
	}
	return true, nil
}

// BlockUser is the resolver for the BlockUser field.
func (r *mutationResolver) BlockUser(ctx context.Context, userID string) (bool, error) {
	currUserID := ctx.Value("TokenHeader").(string)
	user, userErr := service.GetUser(ctx, currUserID)
	blockUser, blockUserErr := service.GetUser(ctx, userID)

	if userErr != nil || blockUserErr != nil {
		return false, userErr
	}

	user.BlockedUser = append(user.BlockedUser, blockUser)
	return true, r.Database.Save(&user).Error
}

// AddSpecificFriend is the resolver for the addSpecificFriend field.
func (r *mutationResolver) AddSpecificFriend(ctx context.Context, friendID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, userErr := service.GetUser(ctx, userID)
	friend, friendErr := service.GetUser(ctx, friendID)

	if userErr != nil || friendErr != nil {
		return false, userErr
	}

	user.SpecificFriend = append(user.SpecificFriend, friend)
	return true, r.Database.Save(&user).Error
}

// RemoveSpecificFriend is the resolver for the removeSpecificFriend field.
func (r *mutationResolver) RemoveSpecificFriend(ctx context.Context, friendID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, userErr := service.GetUser(ctx, userID)
	friend, friendErr := service.GetUser(ctx, friendID)

	if userErr != nil || friendErr != nil {
		return false, userErr
	}

	err := r.Database.Model(&user).Association("SpecificFriend").Delete(friend)
	if err != nil {
		return false, fmt.Errorf("Error removing specific friend: %v", err)
	}
	return true, nil
}

// AcceptGroupInvite is the resolver for the acceptGroupInvite field.
func (r *mutationResolver) AcceptGroupInvite(ctx context.Context, groupID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, err := service.GetUser(ctx, userID)

	if err != nil {
		return false, err
	}

	group, groupErr := service.GetGroup(ctx, groupID)

	if groupErr != nil {
		return false, groupErr
	}

	var invitesToDelete []*model.Group
	for _, invite := range user.GroupInvite {
		if invite.ID == groupID {
			invitesToDelete = append(invitesToDelete, invite)
		}
	}

	err = r.Database.Model(&user).Association("GroupInvite").Delete(&invitesToDelete)
	if err != nil {
		return false, err
	}

	err = r.Database.Model(&group).Association("User").Append(user)
	if err != nil {
		return false, err
	}

	userRole := &model.UserGroupRole{
		UserID:  userID,
		GroupID: groupID,
		Role:    "Member",
	}
	err = r.Database.Save(userRole).Error

	if err != nil {
		return false, err
	}

	_, err = service.AddUserToGroupChat(ctx, userID, groupID)
	if err != nil {
		return false, err
	}

	return true, err
}

// RejectGroupInvite is the resolver for the rejectGroupInvite field.
func (r *mutationResolver) RejectGroupInvite(ctx context.Context, groupID string) (bool, error) {
	userID := ctx.Value("TokenHeader").(string)
	user, err := service.GetUser(ctx, userID)

	if err != nil {
		return false, err
	}

	group, groupErr := service.GetGroup(ctx, groupID)

	if groupErr != nil {
		return false, groupErr
	}

	err = r.Database.Model(&user).Association("GroupInvite").Delete(group)
	if err != nil {
		return false, err
	}

	return true, err
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	return service.GetUser(ctx, id)
}

// GetAllUser is the resolver for the getAllUser field.
func (r *queryResolver) GetAllUser(ctx context.Context) ([]*model.User, error) {
	var users []*model.User

	return users, r.Database.Preload("Friend").Preload("PendingFriend").Preload("BlockedUser").Preload("SpecificFriend").Preload("GroupInvite").Find(&users).Error
}

// GetAllNonFriend is the resolver for the getAllNonFriend field.
func (r *queryResolver) GetAllNonFriend(ctx context.Context, id string) ([]*model.User, error) {
	var users []*model.User
	friendSubquery := r.Database.Table("user_friends").Select("friend_id").Where("user_id = ?", id)

	return users, r.Database.Where("id != ? AND id NOT IN (?)", id, friendSubquery).Preload("Friend").Preload("PendingFriend").Preload("BlockedUser").Preload("SpecificFriend").Preload("GroupInvite").Find(&users).Error
}

// GroupInvite is the resolver for the groupInvite field.
func (r *userResolver) GroupInvite(ctx context.Context, obj *model.User) ([]*model.Group, error) {
	return obj.GroupInvite, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
